Name: SampleConfigurations
Type: FolderType
Children:
- Name: MultistateDisplay_Text
  Id: g=c588d234433fbc55f5b919097b82a339
  Supertype: ColumnLayout
  Description: {"LocaleId":"en-US","Text":"Multi-state text display with embedded Key Value Converter.  Label above value; left justified."}
  ReferenceType: HasComponent
  Children:
  - Name: Label
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      Value: {"NamespaceIndex":-1,"LocaleId":"","Text":""}
      Children:
      - Name: DynamicLink
        Type: DynamicLink
        DataType: NodePath
        Value: "../../Cfg_Label"
    - Name: Style
      Type: BaseDataVariableType
      DataType: String
      ModellingRule: Optional
      Value: "Static Text"
  - Name: Value
    Type: Label
    Children:
    - Name: Text
      Type: BaseDataVariableType
      DataType: LocalizedText
      Value: {"NamespaceIndex":-1,"LocaleId":"","Text":""}
      Children:
      - Name: KeyValueConverter1
        Type: ValueMapConverter
        Children:
        - Name: Source
          Type: BaseDataVariableType
          DataType: BaseDataType
          ReferenceType: HasSource
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../Inp_Value"
        - Name: Pairs
          Type: BaseObjectType
          Children:
          - Name: Pair
            Type: ValueMapPair
            Children:
            - Name: Key
              Type: BaseDataVariableType
              DataType: UInt32
              Value: 0
            - Name: Value
              Type: BaseDataVariableType
              DataType: LocalizedText
              Value: {"LocaleId":"en-US","Text":"Tom"}
          - Name: Pair1
            Type: ValueMapPair
            Children:
            - Name: Key
              Type: BaseDataVariableType
              DataType: UInt32
              Value: 1
            - Name: Value
              Type: BaseDataVariableType
              DataType: LocalizedText
              Value: {"LocaleId":"en-US","Text":"Jerry"}
          - Name: Pair2
            Type: ValueMapPair
            Children:
            - Name: Key
              Type: BaseDataVariableType
              DataType: UInt32
              Value: 2
            - Name: Value
              Type: BaseDataVariableType
              DataType: LocalizedText
              Value: {"LocaleId":"en-US","Text":"Spike"}
    - Name: LeftMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 0.0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 0.0
    - Name: TextHorizontalAlignment
      Type: BaseVariableType
      DataType: TextHorizontalAlignment
      Value: 0
    - Name: Style
      Type: BaseDataVariableType
      DataType: String
      Value: "Default"
      Children:
      - Name: ConditionalConverter1
        Type: ConditionalConverter
        Children:
        - Name: Condition
          Type: BaseDataVariableType
          DataType: Boolean
          ReferenceType: HasSource
          Value: false
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../Cfg_DisplayAsPrimary"
        - Name: TrueValue
          Type: BaseDataVariableType
          DataType: String
          ReferenceType: HasParameter
          ModellingRule: Optional
          Value: "Live Data Primary"
        - Name: FalseValue
          Type: BaseDataVariableType
          DataType: String
          ReferenceType: HasParameter
          ModellingRule: Optional
          Value: "Live Data"
  - Name: Cfg_Label
    Type: BaseDataVariableType
    DataType: LocalizedText
    Description: {"LocaleId":"en-US","Text":"Text description of displayed value."}
    Value: {"LocaleId":"en-US","Text":"Label"}
  - Name: Inp_Value
    Type: BaseDataVariableType
    DataType: UInt32
    Description: {"LocaleId":"en-US","Text":"Input value to be used by the embedded Key Value Converter."}
    Value: 0
  - Name: Cfg_DisplayAsPrimary
    Type: BaseDataVariableType
    DataType: Boolean
    Description: {"LocaleId":"en-US","Text":"Display the value as 'primary' data:  False = Normal weight, True = Bold weight."}
    Value: false
